### ISSUE TITLE
how to provide the container

### ISSUE THREAD

**Issue by jerabaul29** [KTH-FlowAI/DeepReinforcementLearning_RayleighBenard2D_Control#2]
For now the container is on GDrive. This is a bit suboptimal. I personally like to commit it to the repo using github large files system (lfs).

@rvinuesa do you know if the KTH-FlowAI account has a subscription that covers github lfs storage? If so, I can just put the segments on the repo, as I did for example with https://github.com/jerabaul29/Cylinder2DFlowControlDRL/tree/master/container . The nice thing is that things will remain "gathered" this way.

**Comment by rvinuesa** [comment]
According to this, every github should in principle have access to lfs, let's hope it works well here!
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

**Comment by jerabaul29** [comment]
I think without a paid quota the feature is very limited:

[Storage quota](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#storage-quota)

> If you use more than 1 GB of storage without purchasing a data pack, you can still clone repositories with large assets, but you will only retrieve the pointer files, and you will not be able to push new files back up. For more information about pointer files, see "[About Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage#pointer-file-format)."
[Bandwidth quota](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota)
> 
> If you use more than 1 GB of bandwidth per month without purchasing a data pack, Git LFS support is disabled on your account until the next month.

I pay personally around 100USD a year to have the necessary quota on my repositories. It is a bit annoying to pay of course, but the fact that this makes the container available out of the box for everybody is worth it in my opinion :) .

I will check if I can push to this repo with git-lfs. If the quota associated is not enough, do you think adding a git-lfs quota subscription to the KTH-FlowAI account would be relevant? If not, any other "KTH-backed" place where the container segments could be hosted? :) (for now it is hosted on GDrive, which is brittle / Google may discontinue it as they like etc).

**Comment by rvinuesa** [comment]
I see! Please let me know if the quota is not enough, then I will think a bit about the best way to proceed, thank you so much!

**Comment by jerabaul29** [comment]
I try tonight and I let you know :) .

**Comment by jerabaul29** [comment]
actually no time tonight, some other urgent stuff to fix for work, that may have to wait a few days, but I keep you posted :) .

**Comment by rvinuesa** [comment]
Ok great, thank you!

**Comment by jerabaul29** [comment]
I tried to push with git-lfs; it looks good from the terminal:

```
kzm@kzm-bpq:~/Desktop/Current/DeepReinforcementLearning_RayleighBenard2D_Control$ git push
Connection to github.com closed by remote host. MB/s                                                                                                        
Uploading LFS objects: 100% (5/5), 5.2 GB | 2.5 MB/s, done.  
```

however it does not seem to appear on the repository. So I think that with the current subscription, git-lfs is not supported or something like this.

Then we should "just" migrate to a KTH onedrive or similar (and make sure it does not disappear in the future as people change job etc); @franalcantara let us know how this goes :) . Wondering @rvinuesa : do you have an additional "internal KTH archive" on a backed up server for research data that you know will continue to be supported "in all future"? If so, could be good to put a copy of the container part there too (and this may also apply for the container listed from https://github.com/KTH-FlowAI/MARL-drag-reduction-in-wall-bounded-flows i.e. Luca's project).

**Comment by rvinuesa** [comment]
Good idea! @franalcantara let me know if you manage to create the one drive, and when you do it I will save a copy in my own one drive!

**Comment by franalcantara** [comment]
Here you have the link to the KTHOneDrive:

https://kth-my.sharepoint.com/:f:/g/personal/fraa_ug_kth_se/EuT5HqeWx6hPmHDjHihsh2kB-fxXuSf5KH3pXmTbgYmdxw?e=VbxxrD

Let me know if you can download it and if it works properly

**Comment by jerabaul29** [comment]
That works perfectly, many thanks :) .

Closing this, but to keep in the back of our heads: not sure what happens to this container + the container from Luca's work when the respective owners (fraa, lucag) disappear when you move to the next career step - for longer term, may be good to move to @rvinuesa account :) .
